export const MINUTE_MILLISECONDS = 60 * 1000;
export const HOUR_MILLISECONDS = 60 * MINUTE_MILLISECONDS;
export const DAY_MILLISECONDS = 24 * HOUR_MILLISECONDS;
export const WEEK_MILLISECONDS = 7 * DAY_MILLISECONDS;
export const MONTH_MILLISECONDS = 30 * DAY_MILLISECONDS;
export const YEAR_MILLISECONDS = 365 * DAY_MILLISECONDS;

export const MINUTE_SECONDS = 60;
export const HOUR_SECONDS = 60 * MINUTE_SECONDS;
export const DAY_SECONDS = 24 * HOUR_SECONDS;
export const WEEK_SECONDS = 7 * DAY_SECONDS;
export const MONTH_SECONDS = 30 * DAY_SECONDS;
export const YEAR_SECONDS = 365 * DAY_SECONDS;
