name: Publish package

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v7
            - uses: voidzero-dev/setup-vp@v1.21.1
              with:
                  node-version-file: '.node-version'
                  cache: true
            - run: vp exec noeldemartin-publish-package --latest
